// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dl

import (
	"awesomeProject/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	engine, err := service.New()
	if err != nil {
		return nil, nil, err
	}
	app, cleanup, err := NewApp(engine)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
