// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dl

import (
	"awesomeProject/dao"
	"awesomeProject/server"
	"awesomeProject/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	db, cleanup, err := dao.New()
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := dao.NewRedis()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	daoDao := dao.NewDB(db, client)
	serverServer := server.New(daoDao)
	engine, err := service.New(serverServer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup3, err := NewApp(engine, serverServer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
