version: "3"

services:
  db:
    image: mysql:5.7
    entrypoint:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL: 'test'
      MYSQL_PASS: '123456'
    restart: always
    volumes:
       - "./db:/var/lib/mysql"
       - "./conf/my.cnf:/etc/my.cnf"
       - "./init:/docker-entrypoint-initdb.d/"
    ports:
       - "3306:3306"